### ISSUE TITLE
npm break 1.0.26

### ISSUE THREAD

**Issue by steveostop** [sqlanywhere/node-sqlanywhere#45]
When running 'npm i sqlanywhere' after the most recent update, I get an error. 

I can still 'npm i sqlanywhere@1.0.25' perfectly fine.

<details>
  <summary>Here is the npm log when trying to install 1.0.26:</summary>

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '[...]/.nvm/versions/node/v12.22.1/bin/node',
1 verbose cli   '[...]/.nvm/versions/node/v12.22.1/bin/npm',
1 verbose cli   'i',
1 verbose cli   'sqlanywhere'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v12.22.1
4 verbose npm-session f471e0a7aab0fe7a
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/sqlanywhere 447ms (from cache)
8 silly pacote tag manifest for sqlanywhere@latest fetched in 457ms
9 timing stage:loadCurrentTree Completed in 502ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 4ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule sqlanywhere@1.0.26 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/help 9ms (from cache)
18 silly pacote range manifest for help@^3.0.2 fetched in 13ms
19 silly resolveWithNewModule help@3.0.2 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/nan 53ms (from cache)
21 silly pacote version manifest for nan@2.14.2 fetched in 56ms
22 silly resolveWithNewModule nan@2.14.2 checking installable status
23 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 63ms
24 timing stage:loadIdealTree Completed in 70ms
25 silly currentTree micros-pull@1.0.0
25 silly currentTree └── dotenv@16.0.0
26 silly idealTree micros-pull@1.0.0
26 silly idealTree ├── dotenv@16.0.0
26 silly idealTree ├── help@3.0.2
26 silly idealTree ├── nan@2.15.0
26 silly idealTree └─┬ sqlanywhere@1.0.26
26 silly idealTree   └── nan@2.14.2
27 silly install generateActionsToTake
28 timing stage:generateActionsToTake Completed in 3ms
29 silly diffTrees action count 4
30 silly diffTrees add help@3.0.2
31 silly diffTrees add nan@2.15.0
32 silly diffTrees add nan@2.14.2
33 silly diffTrees add sqlanywhere@1.0.26
34 silly decomposeActions action count 32
35 silly decomposeActions fetch help@3.0.2
36 silly decomposeActions extract help@3.0.2
37 silly decomposeActions preinstall help@3.0.2
38 silly decomposeActions build help@3.0.2
39 silly decomposeActions install help@3.0.2
40 silly decomposeActions postinstall help@3.0.2
41 silly decomposeActions finalize help@3.0.2
42 silly decomposeActions refresh-package-json help@3.0.2
43 silly decomposeActions fetch nan@2.15.0
44 silly decomposeActions extract nan@2.15.0
45 silly decomposeActions preinstall nan@2.15.0
46 silly decomposeActions build nan@2.15.0
47 silly decomposeActions install nan@2.15.0
48 silly decomposeActions postinstall nan@2.15.0
49 silly decomposeActions finalize nan@2.15.0
50 silly decomposeActions refresh-package-json nan@2.15.0
51 silly decomposeActions fetch nan@2.14.2
52 silly decomposeActions extract nan@2.14.2
53 silly decomposeActions preinstall nan@2.14.2
54 silly decomposeActions build nan@2.14.2
55 silly decomposeActions install nan@2.14.2
56 silly decomposeActions postinstall nan@2.14.2
57 silly decomposeActions finalize nan@2.14.2
58 silly decomposeActions refresh-package-json nan@2.14.2
59 silly decomposeActions fetch sqlanywhere@1.0.26
60 silly decomposeActions extract sqlanywhere@1.0.26
61 silly decomposeActions preinstall sqlanywhere@1.0.26
62 silly decomposeActions build sqlanywhere@1.0.26
63 silly decomposeActions install sqlanywhere@1.0.26
64 silly decomposeActions postinstall sqlanywhere@1.0.26
65 silly decomposeActions finalize sqlanywhere@1.0.26
66 silly decomposeActions refresh-package-json sqlanywhere@1.0.26
67 silly install executeActions
68 silly doSerial global-install 32
69 verbose correctMkdir [...]/.npm/_locks correctMkdir not in flight; initializing
70 verbose lock using [...]/.npm/_locks/staging-dfafb7ea176f05d9.lock for [...]/node_modules/.staging
71 silly doParallel extract 4
72 silly extract help@3.0.2
73 silly extract nan@2.14.2
74 silly extract sqlanywhere@1.0.26
75 silly extract nan@2.15.0
76 silly tarball trying help@^3.0.2 by hash: sha1-luGQ1KCkU7icLLSwWrOOOo+f2t0=
77 silly tarball trying nan@2.14.2 by hash: sha512-M2ufzIiINKCuDfBSAUr1vWQ+vuVcA9kqx8JJUsbQi6yf1uGRyb7HfpdfUr5qLXf3B/t8dPvcjhKMmlfnP47EzQ==
78 silly tarball trying sqlanywhere@latest by hash: sha512-dNejHqB0KVXpBh1jf1qRouTREWH4NzZqEGyXQTR5eTjZJQf6m8/i8F0njK8D3R3bMlYHTblM4mzo1gGvfwFTog==
79 silly tarball trying nan@2.15.0 by hash: sha512-8ZtvEnA2c5aYCZYd1cvgdnU6cqwixRoYg70xPLWUws5ORTa/lnw+u4amixRS/Ac5U5mQVgp9pnlSUnbNWFaWZQ==
80 silly extract help@^3.0.2 extracted to [...]/node_modules/.staging/help-0ab56616 (41ms)
81 silly extract nan@2.14.2 extracted to [...]/node_modules/.staging/nan-2d564278 (76ms)
82 silly extract nan@2.15.0 extracted to [...]/node_modules/.staging/nan-6f05ad38 (77ms)
83 timing audit submit Completed in 121ms
84 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 121ms
85 timing audit body Completed in 0ms
86 silly extract sqlanywhere@latest extracted to [...]/node_modules/.staging/sqlanywhere-97d245f5 (117ms)
87 timing action:extract Completed in 120ms
88 silly doReverseSerial unbuild 32
89 silly doSerial remove 32
90 silly doSerial move 32
91 silly doSerial finalize 32
92 silly finalize [...]/node_modules/help
93 silly finalize [...]/node_modules/nan
94 silly finalize [...]/node_modules/sqlanywhere/node_modules/nan
95 silly finalize [...]/node_modules/sqlanywhere
96 timing action:finalize Completed in 9ms
97 silly doParallel refresh-package-json 4
98 silly refresh-package-json [...]/node_modules/help
99 silly refresh-package-json [...]/node_modules/nan
100 silly refresh-package-json [...]/node_modules/sqlanywhere/node_modules/nan
101 silly refresh-package-json [...]/node_modules/sqlanywhere
102 timing action:refresh-package-json Completed in 10ms
103 silly doParallel preinstall 4
104 silly preinstall help@3.0.2
105 info lifecycle help@3.0.2~preinstall: help@3.0.2
106 silly preinstall nan@2.15.0
107 info lifecycle nan@2.15.0~preinstall: nan@2.15.0
108 silly preinstall nan@2.14.2
109 info lifecycle nan@2.14.2~preinstall: nan@2.14.2
110 silly preinstall sqlanywhere@1.0.26
111 info lifecycle sqlanywhere@1.0.26~preinstall: sqlanywhere@1.0.26
112 timing action:preinstall Completed in 1ms
113 silly doSerial build 32
114 silly build help@3.0.2
115 info linkStuff help@3.0.2
116 silly linkStuff help@3.0.2 has [...]/node_modules as its parent node_modules
117 silly build nan@2.15.0
118 info linkStuff nan@2.15.0
119 silly linkStuff nan@2.15.0 has [...]/node_modules as its parent node_modules
120 silly build nan@2.14.2
121 info linkStuff nan@2.14.2
122 silly linkStuff nan@2.14.2 has [...]/node_modules/sqlanywhere/node_modules as its parent node_modules
123 silly build sqlanywhere@1.0.26
124 info linkStuff sqlanywhere@1.0.26
125 silly linkStuff sqlanywhere@1.0.26 has [...]/node_modules as its parent node_modules
126 timing action:build Completed in 1ms
127 silly doSerial global-link 32
128 silly doParallel update-linked 0
129 silly doSerial install 32
130 silly install help@3.0.2
131 info lifecycle help@3.0.2~install: help@3.0.2
132 silly install nan@2.15.0
133 info lifecycle nan@2.15.0~install: nan@2.15.0
134 silly install nan@2.14.2
135 info lifecycle nan@2.14.2~install: nan@2.14.2
136 silly install sqlanywhere@1.0.26
137 info lifecycle sqlanywhere@1.0.26~install: sqlanywhere@1.0.26
138 verbose lifecycle sqlanywhere@1.0.26~install: unsafe-perm in lifecycle true
139 verbose lifecycle sqlanywhere@1.0.26~install: PATH: [...]/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:[...]/node_modules/sqlanywhere/node_modules/.bin:[...]/node_modules/.bin:[...]/.nvm/versions/node/v12.22.1/bin:[...]/.nvm/versions/node/v17.4.0/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.8/bin:[...]/mongodb-macos-x86_64-enterprise-4.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:[...]/.nvm/versions/node/v17.4.0/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.8/bin:[...]/.cargo/bin
140 verbose lifecycle sqlanywhere@1.0.26~install: CWD: [...]/node_modules/sqlanywhere
141 silly lifecycle sqlanywhere@1.0.26~install: Args: [ '-c', 'node build.js' ]
142 silly lifecycle sqlanywhere@1.0.26~install: Returned: code: 255  signal: null
143 info lifecycle sqlanywhere@1.0.26~install: Failed to exec install script
144 timing action:install Completed in 2004ms
145 verbose unlock done using [...]/.npm/_locks/staging-dfafb7ea176f05d9.lock for [...]/node_modules/.staging
146 timing stage:rollbackFailedOptional Completed in 27ms
147 timing stage:runTopLevelLifecycles Completed in 2766ms
148 silly saveTree micros-pull@1.0.0
148 silly saveTree ├── dotenv@16.0.0
148 silly saveTree ├── nan@2.15.0
148 silly saveTree └─┬ sqlanywhere@1.0.26
148 silly saveTree   ├── help@3.0.2
148 silly saveTree   └── nan@2.14.2
149 warn micros-pull@1.0.0 No repository field.
150 verbose stack Error: sqlanywhere@1.0.26 install: `node build.js`
150 verbose stack Exit status 255
150 verbose stack     at EventEmitter.<anonymous> ([...]/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
150 verbose stack     at EventEmitter.emit (events.js:314:20)
150 verbose stack     at ChildProcess.<anonymous> ([...]/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
150 verbose stack     at ChildProcess.emit (events.js:314:20)
150 verbose stack     at maybeClose (internal/child_process.js:1022:16)
150 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
151 verbose pkgid sqlanywhere@1.0.26
152 verbose cwd [...]
153 verbose Darwin 19.6.0
154 verbose argv "[...]/bin/node" "[...]/bin/npm" "i" "sqlanywhere"
155 verbose node v12.22.1
156 verbose npm  v6.14.12
157 error code ELIFECYCLE
158 error errno 255
159 error sqlanywhere@1.0.26 install: `node build.js`
159 error Exit status 255
160 error Failed at the sqlanywhere@1.0.26 install script.
160 error This is probably not a problem with npm. There is likely additional logging output above.
161 verbose exit [ 255, true ]
```
</details>

**Comment by DanCummins-SAP** [comment]
Hi Steve,

I noticed that the new package is missing the nodever_cover.h in src/h.
As a workaround until we can repost, you can get it from the 1.0.25 package.

Dan

**Comment by steveostop** [comment]
Got it, thanks Dan.

**Comment by DanCummins-SAP** [comment]
I published sqlanywhere-1.0.27.tgz that contains a fix.
Could you let me know that it works for you?
Thanks,
Dan

**Comment by DanCummins-SAP** [comment]
I republished the package as sqlanywhere-1.0.27.tgz
Thanks,
Dan
